### ISSUE TITLE
Ver 3.2.2 Resolve error: typescript with invalid interface loaded as resolver

### ISSUE THREAD

**Issue by alecthw** [import-js/eslint-import-resolver-typescript#141] opened 2022-07-06 02:44 UTC
when update to Ver. 3.2.2, these errors:
```
  1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-unresolved
  1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/order
  1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-self-import
  1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/extensions
```
3.2.1 is OK

**Comment by JounQin** [comment] 2022-07-06 02:45
duplicate of #135

**Closed** 2022-07-06 02:45 UTC
