### ISSUE TITLE
cannot read project file 'tsconfig.json' with 'references' to sub config files.

### ISSUE THREAD

**Issue by Nick-Hopps** [import-js/eslint-import-resolver-typescript#257] opened 2023-11-28 13:31 UTC
my tsconfig.json file is like this: 

```json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.node.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

and I have different settings based on different files, such as tsconfig.app.json: 

```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "baseUrl": ".",
    "composite": true,
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": ["element-plus/global.d.ts"]
  }
}
```

I have to configure tsconfig file specifically with 'path' in em to make it work:

```js
{
  'import/parsers': {
    '@typescript-eslint/parser': ['.ts', '.tsx'],
  },
  'import/resolver': {
    'typescript': {
      'project': './tsconfig.app.json',
    },
  },
}
```

**Comment by JounQin** [comment] 2023-11-28 13:37
Duplicate of #94

**Closed** 2023-11-28 13:37 UTC
