### ISSUE TITLE
Incorrect path resolved when monorepo project contains multiple tsconfig.json

### ISSUE THREAD

**Issue by nicedu-123** [import-js/eslint-import-resolver-typescript#168] opened 2022-08-16 07:10 UTC
This is the architecture of the project:
```
 packages/
      projectA/
           tsconfig.json
      projectB/
           tsconfig.json
eslintrc.js
tsconfig.json
```
tsconfig.json in projectA
```
{
    ...
    "paths": {
      "@/*": [
          "./src/*"
    ],
    ...
}
```

tsconfig.json in projectB have same path definition
```
{
    ...
    "paths": {
      "@/*": [
          "./src/*"
    ],
    ...
}
```

and the configuration of eslint-import-resolver-typescript

```
  settings: {
    "import/resolver": {
      "typescript": {
        project: [
          "packages/*/tsconfig.json",
          "tsconfig.json"
        ]
      }
    },
  }
```
when using `import @/xxxxx` in projectB,  it will match the path to project A。
actually this resolver got multiple paths, and return paths[0]。
Is it possible to tell which project a file belongs to, , and return the correct path。

**Comment by JounQin** [comment] 2022-08-16 08:34
Duplicate of https://github.com/import-js/eslint-import-resolver-typescript/issues/87#issuecomment-998406411

**Closed by JounQin** 2022-08-16 08:34 UTC
